### ISSUE TITLE
Support schematron "let" keyword

### ISSUE THREAD

**Issue by jonherrmann** [interactive-instruments/etf-ets-repository#4]
@thijsbrentjens

The XSLT stylesheet does not yet support the schema 'let' keyword.

**Comment by thijsbrentjens** [comment]
Thanks for letting it know, I'll wait for this before migrating our schematron validators.

**Comment by thijsbrentjens** [comment]
I tried the XSL to transform schematron that uses the let element and uses that in an assertion. E.g.: 

`<sch:let name="fileIdentifier" value="normalize-space(gmd:fileIdentifier/gco:CharacterString)"/>`

And in an assertion:
`<sch:assert id="Metadata ID (ISO nr. 2)" test="$fileIdentifier">Er is geen Metadata ID (ISO nr. 2) opgegeven.</sch:assert>`

The XSL is not able to transform that properly to a working expression. Because it uses the attribute `@test` with the variable directly to create an expression:

`let $filesWithErrors := $db[<xsl:value-of select="$schContext"/>[not(<xsl:value-of select="@test"/>)]]`

Which results in errors like:

`[err:XPDY0002] gmd:fileIdentifier: no context value bound. `

Do you have any idea if this can ben resolved (in a generic way)?

**Comment by jonherrmann** [comment]
Can you check if you have added the gmd namespace to the testquery.xq file?

From the [docs](https://github.com/interactive-instruments/etf-ets-repository/tree/master/utils#transform-a-schematron-file-to-an-etf-version-2-executable-test-suite):
```
If your Schematron file uses namespaces that are not declared in the testquery.xq file, they must be manually added in the form:

declare namespace nsPrefix='http://namespace-uri';
```

**Comment by thijsbrentjens** [comment]
The namespaces of metadata (gmd, gco etc) are present. I've configured several validators. Could these interfere?
